os:
  - linux
language: go
go:
  - 1.9
sudo: required

services:
  - docker

cache:
  directories:
    - $GOPATH/pkg
    - $GOPATH/src/github.com/bmeg/arachne/.git/modules
    - $GOPATH/src/github.com/bmeg/arachne/vendor

git:
  submodules: false

install:
  - make depends
  - make

jobs:
  include:
    - stage: all
      script: make lint
      env:
        - n=lint
    - script:
      - make test
      env:
        - n=tests
    - script:
      - arachne server --rpc 18202 --port 18201 &
      - sleep 5
      - make test-conformance
      env:
        - n=badger
    - script:
      - arachne server --rpc 18202 --port 18201 --bolt arachne.db &
      - sleep 5
      - make test-conformance
      env:
        - n=boltdb
    - script:
      - arachne server --rpc 18202 --port 18201 --rocks arachne.db &
      - sleep 5
      - make test-conformance
      env:
        - n=rocksdb
    - script:
      - arachne server --rpc 18202 --port 18201 --level arachne.db &
      - sleep 5
      - make test-conformance
      env:
        - n=leveldb
    - script:
      - make start-test-mongo-database
      - sleep 5
      - arachne server --rpc 18202 --port 18201 --mongo localhost:27000 &
      - sleep 5
      - make test-conformance
      env:
        - n=mongodb
    - script:
      - make start-test-elastic-database
      - sleep 5
      - arachne server --rpc 18202 --port 18201 --elastic http://localhost:9200 &
      - sleep 5
      - make test-conformance
      env:
        - n=elasticsearch

notifications:
  email: false
